# PaperFetch Configuration File
# This file contains configuration parameters for the CrossRef API search

[search]
# The search query to use for finding papers
query = "the query you are looking for!"
# Maximum number of papers to process with LLM (set to 0 to disable LLM processing entirely)
max_papers_for_llm = 100

[api]
# Email address for CrossRef API requests (required for polite usage)
mailto = "yourmailaddress@mail.com"
openai_api = "sk-XXXXXX"
openai_url = "http://someapiurl.com/api/v1"
openai_model = "somemodel"

[email]
# Email configuration for sending results
smtp_server = "smtp.gmail.com"
smtp_port = 587
sender_email = "yourmailaddress@mail.com"
sender_password = "your_app_password"
recipient_email = "recipient@mail.com"
subject_prefix = "PaperFetch Results"