# PaperFetch Configuration File
# This file contains configuration parameters for the CrossRef API search

[search]
# The search query to use for finding papers
# Can be a list of terms or a single string (for backward compatibility)
# When using a list, terms are joined with spaces for CrossRef and with " AND " for Nature/Springer
query = ["single-cell", "tissue ecosystem"]
# Alternative single string format (deprecated but still supported):
# query = "single-cell tissue ecosystem"

# Optional: a short text describing the researcher's current interests.
# If provided, this text will be included in the LLM prompt and used alongside the query.
researcher_interests = """
I am currently developing a VAE model for scRNASeq that enhances interpretability. 
I am interested in causal inference, health data, cancer research"""
# Maximum number of papers to process with LLM (set to 0 to disable LLM processing entirely)
max_papers_for_llm = 100

[api]
# Email address for CrossRef API requests (required for polite usage)
mailto = "yourmailaddress@mail.com"
openai_api = "sk-XXXXXX"
openai_url = "http://someapiurl.com/api/v1"
openai_model = "somemodel"
max_attempts = 3
ssl_verify = true

# Nature/Springer API configuration (optional)
# Set enable_springer to true to also search Nature/Springer databases
enable_springer = false
springer_api_key = "your_springer_api_key_here"

[email]
# Email configuration for sending results
smtp_server = "smtp.gmail.com"
smtp_port = 587
sender_email = "yourmailaddress@mail.com"
sender_password = "your_app_password"
recipient_email = "recipient@mail.com"
subject_prefix = "PaperFetch Results"
